CREATE TABLE `sample_table` (`no` INTEGER, `name` TEXT, `height` NUMERIC, `age` INTEGER, PRIMARY KEY (`no`, `name`));
INSERT INTO `sample_table` VALUES (1,'lee',185.5,25);
INSERT INTO `sample_table` VALUES (2,'jung',193.8,0);
INSERT INTO `sample_table` VALUES (3,'park',170.0,27);
INSERT INTO `sample_table` VALUES (4,'kim',180.0,27);
INSERT INTO `sample_table` VALUES (5,'sim',null,null);
CREATE TABLE `sample_table2` (`no` INTEGER, `phone` TEXT);
INSERT INTO `sample_table2` VALUES (1,'010-1234-5678');
INSERT INTO `sample_table2` VALUES (1,'010-9123-4567');
INSERT INTO `sample_table2` VALUES (1,'010-2222-1111');
INSERT INTO `sample_table2` VALUES (1,'010-3333-4444');
INSERT INTO `sample_table2` VALUES (1,'010-5555-6666');
INSERT INTO `sample_table2` VALUES (2,null);
CREATE TABLE `sample_table3` (`id` INTEGER);
INSERT INTO `sample_table3` VALUES (1);
INSERT INTO `sample_table3` VALUES (2);
INSERT INTO `sample_table3` VALUES (0);
INSERT INTO `sample_table3` VALUES (4);
INSERT INTO `sample_table3` VALUES (4);
INSERT INTO `sample_table3` VALUES (4);
INSERT INTO `sample_table3` VALUES (4);
INSERT INTO `sample_table3` VALUES (8);
INSERT INTO `sample_table3` VALUES (9);
INSERT INTO `sample_table3` VALUES (10);
